### ISSUE TITLE
Baud rate (115200) might cause problems (?)

### ISSUE THREAD

**Issue by stozk** [openhomeautomation/wifi-weather-station#3]
Hi,

I've run into some trouble with the sensor test and weather station sketches.
(1.5.7 & 1.5.8 IDE)

When using a baud rate of 115200 as it's set in the sketches my Uno would crap out after like 2 readings and the serial monitor would only display gibberish.
The weather station also wouldn't work, it would only display like:

>{"temperature": 17, "id": "1", "nam

and crash after that.

After reducing the baud rate to 9600 in both sketches it works like a charm now.

Maybe someone knows what the problem might be.
Faulty USB cable? Faulty Arduino Uno R3? I've switched the sensors too.
I've tried the sensor test sketch with an Arduino Leonardo clone and it worked with 115200, but the weather station sketch wouldn't work because of low memory.

BR
Daniel

**Comment by marcoschwartz** [comment]
That's an interesting comment, thanks for letting me know. I will make sure to switch all the debug outputs to 9600 from now on, as there is no reason to use a higher rate.

**Comment by marcoschwartz** [comment]
Done for this project!
